/*
    File: timezone-data.js
    Last modified: 04.12.2025 13:56 MEZ
*/

// Timezone abbreviations with full name and IANA timezone
// Alphabetically sorted by abbreviation
const timezoneAbbreviations = [
    { abbr: 'ACDT', name: 'Australian Central Daylight Time', iana: 'Australia/Adelaide', offset: '+10:30' },
    { abbr: 'ACST', name: 'Australian Central Standard Time', iana: 'Australia/Adelaide', offset: '+09:30' },
    { abbr: 'ADT', name: 'Atlantic Daylight Time', iana: 'America/Halifax', offset: '-03:00' },
    { abbr: 'AEDT', name: 'Australian Eastern Daylight Time', iana: 'Australia/Sydney', offset: '+11:00' },
    { abbr: 'AEST', name: 'Australian Eastern Standard Time', iana: 'Australia/Sydney', offset: '+10:00' },
    { abbr: 'AKDT', name: 'Alaska Daylight Time', iana: 'America/Anchorage', offset: '-08:00' },
    { abbr: 'AKST', name: 'Alaska Standard Time', iana: 'America/Anchorage', offset: '-09:00' },
    { abbr: 'AST', name: 'Atlantic Standard Time', iana: 'America/Halifax', offset: '-04:00' },
    { abbr: 'AWST', name: 'Australian Western Standard Time', iana: 'Australia/Perth', offset: '+08:00' },
    { abbr: 'BST', name: 'British Summer Time', iana: 'Europe/London', offset: '+01:00' },
    { abbr: 'CAT', name: 'Central Africa Time', iana: 'Africa/Johannesburg', offset: '+02:00' },
    { abbr: 'CDT', name: 'Central Daylight Time', iana: 'America/Chicago', offset: '-05:00' },
    { abbr: 'CEST', name: 'Central European Summer Time', iana: 'Europe/Berlin', offset: '+02:00' },
    { abbr: 'CET', name: 'Central European Time', iana: 'Europe/Berlin', offset: '+01:00' },
    { abbr: 'CST', name: 'Central Standard Time', iana: 'America/Chicago', offset: '-06:00' },
    { abbr: 'EAT', name: 'East Africa Time', iana: 'Africa/Nairobi', offset: '+03:00' },
    { abbr: 'EDT', name: 'Eastern Daylight Time', iana: 'America/New_York', offset: '-04:00' },
    { abbr: 'EEST', name: 'Eastern European Summer Time', iana: 'Europe/Athens', offset: '+03:00' },
    { abbr: 'EET', name: 'Eastern European Time', iana: 'Europe/Athens', offset: '+02:00' },
    { abbr: 'EST', name: 'Eastern Standard Time', iana: 'America/New_York', offset: '-05:00' },
    { abbr: 'GMT', name: 'Greenwich Mean Time', iana: 'Europe/London', offset: '+00:00' },
    { abbr: 'GST', name: 'Gulf Standard Time', iana: 'Asia/Dubai', offset: '+04:00' },
    { abbr: 'HKT', name: 'Hong Kong Time', iana: 'Asia/Hong_Kong', offset: '+08:00' },
    { abbr: 'HST', name: 'Hawaii Standard Time', iana: 'Pacific/Honolulu', offset: '-10:00' },
    { abbr: 'ICT', name: 'Indochina Time', iana: 'Asia/Bangkok', offset: '+07:00' },
    { abbr: 'IDT', name: 'Israel Daylight Time', iana: 'Asia/Jerusalem', offset: '+03:00' },
    { abbr: 'IST', name: 'India Standard Time', iana: 'Asia/Kolkata', offset: '+05:30' },
    { abbr: 'IST', name: 'Irish Standard Time', iana: 'Europe/Dublin', offset: '+01:00' },
    { abbr: 'IST', name: 'Israel Standard Time', iana: 'Asia/Jerusalem', offset: '+02:00' },
    { abbr: 'JST', name: 'Japan Standard Time', iana: 'Asia/Tokyo', offset: '+09:00' },
    { abbr: 'KST', name: 'Korea Standard Time', iana: 'Asia/Seoul', offset: '+09:00' },
    { abbr: 'MDT', name: 'Mountain Daylight Time', iana: 'America/Denver', offset: '-06:00' },
    { abbr: 'MESZ', name: 'Mitteleuropäische Sommerzeit', iana: 'Europe/Berlin', offset: '+02:00' },
    { abbr: 'MEZ', name: 'Mitteleuropäische Zeit', iana: 'Europe/Berlin', offset: '+01:00' },
    { abbr: 'MSK', name: 'Moscow Standard Time', iana: 'Europe/Moscow', offset: '+03:00' },
    { abbr: 'MST', name: 'Mountain Standard Time', iana: 'America/Denver', offset: '-07:00' },
    { abbr: 'NZDT', name: 'New Zealand Daylight Time', iana: 'Pacific/Auckland', offset: '+13:00' },
    { abbr: 'NZST', name: 'New Zealand Standard Time', iana: 'Pacific/Auckland', offset: '+12:00' },
    { abbr: 'PDT', name: 'Pacific Daylight Time', iana: 'America/Los_Angeles', offset: '-07:00' },
    { abbr: 'PKT', name: 'Pakistan Standard Time', iana: 'Asia/Karachi', offset: '+05:00' },
    { abbr: 'PST', name: 'Pacific Standard Time', iana: 'America/Los_Angeles', offset: '-08:00' },
    { abbr: 'SAST', name: 'South Africa Standard Time', iana: 'Africa/Johannesburg', offset: '+02:00' },
    { abbr: 'SGT', name: 'Singapore Time', iana: 'Asia/Singapore', offset: '+08:00' },
    { abbr: 'SST', name: 'Singapore Standard Time', iana: 'Asia/Singapore', offset: '+08:00' },
    { abbr: 'UTC', name: 'Coordinated Universal Time', iana: 'UTC', offset: '+00:00' },
    { abbr: 'WAT', name: 'West Africa Time', iana: 'Africa/Lagos', offset: '+01:00' },
    { abbr: 'WEST', name: 'Western European Summer Time', iana: 'Europe/Lisbon', offset: '+01:00' },
    { abbr: 'WET', name: 'Western European Time', iana: 'Europe/Lisbon', offset: '+00:00' },
    { abbr: 'WIB', name: 'Western Indonesian Time', iana: 'Asia/Jakarta', offset: '+07:00' },
    { abbr: 'WIT', name: 'Eastern Indonesian Time', iana: 'Asia/Jayapura', offset: '+09:00' },
    { abbr: 'WITA', name: 'Central Indonesian Time', iana: 'Asia/Makassar', offset: '+08:00' }
];

// Country to timezone abbreviation mapping
const countryToAbbreviation = {
    'germany': 'CET',
    'deutschland': 'CET',
    'austria': 'CET',
    'österreich': 'CET',
    'switzerland': 'CET',
    'schweiz': 'CET',
    'france': 'CET',
    'frankreich': 'CET',
    'spain': 'CET',
    'spanien': 'CET',
    'italy': 'CET',
    'italien': 'CET',
    'netherlands': 'CET',
    'niederlande': 'CET',
    'holland': 'CET',
    'belgium': 'CET',
    'belgien': 'CET',
    'poland': 'CET',
    'polen': 'CET',
    'czech': 'CET',
    'tschechien': 'CET',
    'czech republic': 'CET',
    'tschechische republik': 'CET',
    'uk': 'GMT',
    'united kingdom': 'GMT',
    'großbritannien': 'GMT',
    'england': 'GMT',
    'ireland': 'GMT',
    'irland': 'GMT',
    'portugal': 'WET',
    'greece': 'EET',
    'griechenland': 'EET',
    'turkey': 'EET',
    'türkei': 'EET',
    'russia': 'MSK',
    'russland': 'MSK',
    'usa': 'EST',
    'united states': 'EST',
    'vereinigte staaten': 'EST',
    'america': 'EST',
    'amerika': 'EST',
    'new york': 'EST',
    'washington': 'EST',
    'boston': 'EST',
    'miami': 'EST',
    'chicago': 'CST',
    'texas': 'CST',
    'houston': 'CST',
    'dallas': 'CST',
    'denver': 'MST',
    'phoenix': 'MST',
    'los angeles': 'PST',
    'san francisco': 'PST',
    'seattle': 'PST',
    'california': 'PST',
    'kalifornien': 'PST',
    'canada': 'EST',
    'kanada': 'EST',
    'toronto': 'EST',
    'montreal': 'EST',
    'vancouver': 'PST',
    'mexico': 'CST',
    'mexiko': 'CST',
    'brazil': 'UTC',
    'brasilien': 'UTC',
    'argentina': 'UTC',
    'argentinien': 'UTC',
    'chile': 'UTC',
    'japan': 'JST',
    'tokio': 'JST',
    'tokyo': 'JST',
    'china': 'HKT',
    'beijing': 'HKT',
    'peking': 'HKT',
    'shanghai': 'HKT',
    'india': 'IST',
    'indien': 'IST',
    'thailand': 'ICT',
    'bangkok': 'ICT',
    'vietnam': 'ICT',
    'singapore': 'SGT',
    'singapur': 'SGT',
    'south korea': 'KST',
    'südkorea': 'KST',
    'korea': 'KST',
    'seoul': 'KST',
    'australia': 'AEST',
    'australien': 'AEST',
    'sydney': 'AEST',
    'melbourne': 'AEST',
    'new zealand': 'NZST',
    'neuseeland': 'NZST',
    'auckland': 'NZST',
    'south africa': 'SAST',
    'südafrika': 'SAST',
    'egypt': 'EET',
    'ägypten': 'EET',
    'uae': 'GST',
    'vae': 'GST',
    'dubai': 'GST',
    'united arab emirates': 'GST',
    'vereinigte arabische emirate': 'GST',
    'saudi arabia': 'GST',
    'saudi-arabien': 'GST',
    'israel': 'IST',
    'norway': 'CET',
    'norwegen': 'CET',
    'sweden': 'CET',
    'schweden': 'CET',
    'denmark': 'CET',
    'dänemark': 'CET',
    'finland': 'EET',
    'finnland': 'EET',
    'iceland': 'GMT',
    'island': 'GMT',
    'hawaii': 'HST',
    'hong kong': 'HKT',
    'hongkong': 'HKT',
    'pakistan': 'PKT',
    'indonesia': 'WIB',
    'indonesien': 'WIB',
    'jakarta': 'WIB'
};
